### ISSUE TITLE
Team report from YT

### ISSUE THREAD

**Issue by georgeee** [serokell/yt-utilities#12]
To export issues on daily for team and for each person individually:

* Report should be used:
  * This month: [UI](https://issues.serokell.io/reports/time/113-245), [REST API](https://issues.serokell.io/rest/current/reports/113-245?fields=reportData)
  * Prev month:  [UI](https://issues.serokell.io/reports/time/113-244), [REST API](https://issues.serokell.io/rest/current/reports/113-244?fields=reportData)
  * (For both visibility group is serokell)

* To calculate stats:
  * Trigger recalculate via REST API (see snippet below) 
  * Get report data (see url above), parse it to `HM.HashMap Day (HM.HashMap UserName [IssueId])`
  * For daily report for whole team: pick up day, import tracks for all issues which occur in map for the day
    * For individual daily report: same, but filter by user before importing all subitems

Recalculation API:
```
PUT https://issues.serokell.io/rest/current/reports/113-245/recalculate
Body: {id: "113-245"}
```

**Comment by georgeee** [comment]
You should use `subcommand` feature of `optparse` library to have:
`./Export.hs export` for current functionality
`./Export.hs report` for described in this issue

Also, let's rename `Export.hs` to `YT.hs`?

**Comment by georgeee** [comment]
Let's format report as CSV table:

||Day||User||IssueId||Desc||Duration||

Also, please add to CLI options for reporting tool:
* `--since` to create report from particular date
* `--user` to filter on particular user

**Comment by ChShersh** [comment]
Aborted because of #29
