### ISSUE TITLE
Lines with half-open clocks result in parse error instead of ignoring them

### ISSUE THREAD

**Issue by ChShersh** [serokell/yt-utilities#14]
I have next line in my `.org` file:

```
    CLOCK: [2017-08-12 Sat 17:51]
```

Running `Export ` I see next error:

```
Export.hs: Ambiguous line: "    CLOCK: [2017-08-12 Sat 17:51]", most probably there is an error in syntax
```

I think such lines should be ignored instead of printing error.

**Comment by volhovM** [comment]
@ChShersh done in `92e90c93a82df40044e7540403789e241713c536`

**Comment by ChShersh** [comment]
Tested. Works.
