### ISSUE TITLE
Enable -Wall, fix warnings

### ISSUE THREAD

**Issue by gromakovsky** [serokell/yt-utilities#19]
I noticed there are many warnings if I enable `-Wall`. It would be good to fix them and enable `-Wall`.

**Comment by ChShersh** [comment]
@gromakovsky I didn't find a way to enable `-Wall` and opened #16.
`-Wall` can be enabled for `ghci` but not for `stack script` or `stack runghc`.

**Comment by gromakovsky** [comment]
Aha, ok, I added 👍 reaction to #16. Then I think this issue doesn't make sense.
